In [1]:
!pip install numpy

In [5]:
import numpy as np
import time

In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int64


In [13]:
import time

py_list = list(range(1_000_000))
py_result = []

start_time = time.time()
for i in py_list:
    py_result.append(i + 5)
end_time = time.time()

print("Python List Time:", end_time - start_time)

Python List Time: 0.33411598205566406


In [14]:
import numpy as np
import time

np_array = np.arange(1_000_000)

start_time = time.time()
np_result = np_array + 5
end_time = time.time()

print("NumPy Array Time:", end_time - start_time)

NumPy Array Time: 0.11291885375976562


In [15]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [18]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
print(np.full((2,3), 7))

[[7 7 7]
 [7 7 7]]


In [23]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [24]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [25]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [30]:
np.array([1,2,3] , dtype = float)

array([1., 2., 3.])

In [31]:
np.array([1.5,2.3,3.6])
print(arr.astype(int))

[1 2 3]


In [32]:
import numpy as np

# Creating a 2D array (3x3 matrix)
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [33]:
print(arr[0, 1])  # Output: 20 (row 0, col 1)
print(arr[2, 2])  # Output: 90 (row 2, col 2)

# Negative Indexing (counting from the end)
print(arr[-1, -2]) # Output: 80 (last row, 2nd last column)
print(arr[-3, -3]) # Output: 10 (first row, first column)

20
90
80
10


In [34]:
# General form: arr[start:stop:step]
print(arr[0:2, 1:3]) # Output: rows 0-1, cols 1-2

# Striding: skipping elements
print(arr[::2, ::2]) # Output: every 2nd row & 2nd column

[[20 30]
 [50 60]]
[[10 30]
 [70 90]]


In [35]:
# Slicing creates a "view" (editing the slice affects the original)
slice_arr = arr[0, :2] # view (not a copy)
slice_arr[0] = 999

print(arr[0])          # Original changes to [999, 20, 30]

# Using .copy() creates an independent object
copy_arr = arr[1].copy() # independent copy
copy_arr[0] = 555

print(arr[1])          # Original remains unchanged

[999  20  30]
[40 50 60]


In [43]:
# Random generator with seed for reproducibility
rng = np.random.default_rng(seed = 43)
flips = rng.integers(0, 2, size = 100000)
pro_heads = np.mean(flips)
print("Estimated probability of heads : ", pro_heads)

Estimated probability of heads :  0.50238


In [44]:
# Simulate 100k coin flips
rng = np.random.default_rng(seed=43)
flips = rng.integers(0, 2, size=100000) # 0 = tails, 1 = heads
prob_heads = np.mean(flips)
print("Estimated probability of heads:", prob_heads)

import time

# Python loop
start = time.time()
squares = [i**2 for i in range(1000000)]
end = time.time()
print("Loop time:", end - start)

# NumPy vectorized
start = time.time()
arr = np.arange(1000000)
squares_np = arr**2
end = time.time()
print("Vectorized time:", end - start)

Estimated probability of heads: 0.50238
Loop time: 0.23979640007019043
Vectorized time: 0.00508570671081543
